receivers:
  zipkin:

processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"

service:
  telemetry:
    logs:
      level: "debug"

  pipelines:
    traces:
      receivers: [zipkin]
      processors: [batch]
      exporters: [otlp]
